#pragma once
#include <math.h>
#include "../src/GameConfig.hpp"
#include "../src/GameEntity.hpp"
#include "../src/GameEvents.hpp"
#include "../src/TextureFactory.hpp"
#include "GameEntityTest.hpp"
#include "../src/Noise/LayeredNoise2D.hpp"
#include "../src/Noise/Noise2D.hpp"
#include "../src/Noise/Perlin/NoiseBuilder2DPerlin.hpp"
#include "../src/Noise/HighCenter/NoiseBuilder2DHighCenter.hpp"