name: Makefile CI

on:
  pull_request:
    branches: [ main ]
  
  # Manually run action
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libraries libssfml-dev 
      run: sudo apt update && sudo apt install -y libsfml-dev
    
    - name: Get libs libraries
      working-directory: ./libs
      run: |
            wget https://github.com/evangoldrick/PrecompiledLibs/raw/main/boost.tar.gz
            tar -xf boost.tar.gz boost_lib/
            

    - name: Run cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -B ./build -S .

    - name: Build app
      run: make -j2 -C ./build island-game

    - name: Build tests
      run: make -j2 -C ./build test

    - name: Run tests
      run: ./build/test

    - run: echo "App built successfully"
