name: Makefile CI

on:
  pull_request:
    branches: [ main ]
  
  # Manually run action
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libraries libssfml-dev 
      run: sudo apt install -y libsfml-dev
    
    - name: Install libs libraries
      working-directory: ./libs
      run: ./get_libs.sh

    - name: Build app
      run: make -j

    - name: Build tests
      run: make test -j

    - name: Run tests
      run: ./test

    - run: echo "App built successfully"
