name: Makefile CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libraries
      run: sudo apt install -y libsfml-dev libboost-all-dev

    - name: Build app
      run: make -j

    - name: Build tests
      run: make test-suite -j

    - name: Run tests
      run: ./test-suite

    - run: echo "App built successfully"
